{
 "title": "Networth",
 "description": "Leveraging eBPF and XDP for monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Networth World Map",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "geoip{}", "legendFormat": "{{city}}" }
   ]
  },
  {
   "title": "Total Bytes Recieved",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sum(bytes_per_ip)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP Protocols",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "protocol_data_total", "legendFormat": "{{protocol}}" }
   ]
  },
  {
   "title": "CPU % used by NetWorth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[15s]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}